In [1]:
import os 
import sys
import pandas as pd 
import numpy as np

folder = './data/quorumsims_test_small/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv') and file.startswith('1')]
meta = pd.read_csv(folder+'metadata.csv')

In [2]:
submeta = pd.DataFrame([],columns=meta.columns)
submeta

Empty DataFrame
Columns: [file_name, site_qualities, site_positions, hub_position, num_agents, site_converged, time_converged, start_state, maxTime]
Index: []

In [3]:
import pdb
# files.remove('metadata.csv')
for file in files:
    
    row = meta.loc[meta.file_name==file].values
    # print(row, len(row[0]))
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # break
submeta

,file_name,site_qualities,site_positions,hub_position,num_agents,site_converged,time_converged,start_state,maxTime
0,1719965077324195.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.769,987,"(('EXPLORE', None), ('EXPLORE', None), ('EXPLO...",35000
1,1719965077322241.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.769,551,"(('EXPLORE', None), ('EXPLORE', None), ('EXPLO...",35000
2,1719965077323017.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.819,456,"(('RECRUIT', 3), ('EXPLORE', None), ('EXPLORE'...",35000
3,1719965077329089.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.769,291,"(('EXPLORE', None), ('EXPLORE', None), ('EXPLO...",35000
4,1719965077322888.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.769,1333,"(('RECRUIT', 3), ('EXPLORE', None), ('EXPLORE'...",35000
...,...,...,...,...,...,...,...,...,...
182,1719965077323557.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.769,484,"(('RECRUIT', 2), ('EXPLORE', None), ('EXPLORE'...",35000
183,1719965077331153.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.769,1085,"(('EXPLORE', None), ('EXPLORE', None), ('RECRU...",35000
184,1719965077323740.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.769,528,"(('RECRUIT', 2), ('EXPLORE', None), ('EXPLORE'...",35000
185,1719965077329251.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.769,766,"(('RECRUIT', 0), ('EXPLORE', None), ('EXPLORE'...",35000
186,1719965077323387.csv,"[0.459, 0.819, 0.769, 0.168]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.819,359,"(('EXPLORE', None), ('EXPLORE', None), ('RECRU...",35000

In [4]:
from ast import literal_eval
submeta.site_qualities=submeta.site_qualities.apply(literal_eval)
submeta.site_positions=submeta.site_positions.apply(literal_eval)
submeta.site_qualities=submeta.site_qualities.apply(lambda x: tuple(x))
submeta.site_positions=submeta.site_positions.apply(lambda x: tuple([tuple(a) for a in x]))

df = submeta.groupby(by=['site_qualities', 'site_positions', 'num_agents'], as_index=False).agg(lambda x: x.tolist())

In [5]:
df['numentries'] = df.maxTime.apply(lambda x: len(x))
df.numentries

0    187
Name: numentries, dtype: int64

In [6]:
files_to_save_one_graph = df.iloc[0]['file_name']

# import os 
# import shutil
# import numpy as np
# fold = '../final_experiments/allGraphs_train/'
# fold_new = '../final_experiments/allGraphs_test/'
# files = os.listdir(fold)
# for file in files[:-1]:
#     if np.random.random() > 0.7:
#         print(file)
#         shutil.move(fold+file, fold_new+file)

In [7]:
len(files_to_save_one_graph)

187

In [8]:
import shutil
# for file in files_to_save_one_graph:
# # try:
#     shutil.copy(folder+file, './data/quorumsims_fixed_otheragents/'+file)
#     # except:
#         # continue

In [9]:
print(files_to_save_one_graph)
for file in files_to_save_one_graph:
    if np.random.random() < 0.9:
        # print(file)
        shutil.move(folder+file, 'data/quorumsims_test_small/train/'+file)

['1719965077324195.csv', '1719965077322241.csv', '1719965077323017.csv', '1719965077329089.csv', '1719965077322888.csv', '1719965077323994.csv', '1719965077323770.csv', '1719965077322485.csv', '1719965077321761.csv', '1719965077323360.csv', '1719965077322054.csv', '1719965077330691.csv', '1719965077326018.csv', '1719965077323799.csv', '1719965077324544.csv', '1719965077324020.csv', '1719965077326151.csv', '1719965077330914.csv', '1719965077326227.csv', '1719965077322733.csv', '1719965077322914.csv', '1719965077324346.csv', '1719965077331039.csv', '1719965077331011.csv', '1719965077321955.csv', '1719965077329448.csv', '1719965077322858.csv', '1719965077324226.csv', '1719965077329064.csv', '1719965077324568.csv', '1719965077326197.csv', '1719965077331399.csv', '1719965077330087.csv', '1719965077329475.csv', '1719965077330859.csv', '1719965077323825.csv', '1719965077330440.csv', '1719965077329663.csv', '1719965077329844.csv', '1719965077331562.csv', '1719965077329503.csv', '1719965077330721.csv', '1719965077329310.csv', '1719965077322709.csv', '1719965077321298.csv', '1719965077323855.csv', '1719965077329559.csv', '1719965077323048.csv', '1719965077331129.csv', '1719965077323277.csv', '1719965077330169.csv', '1719965077330196.csv', '1719965077330343.csv', '1719965077322790.csv', '1719965077326284.csv', '1719965077330382.csv', '1719965077331077.csv', '1719965077322989.csv', '1719965077321933.csv', '1719965077321700.csv', '1719965077331507.csv', '1719965077321072.csv', '1719965077323936.csv', '1719965077330779.csv', '1719965077331315.csv', '1719965077331103.csv', '1719965077326330.csv', '1719965077323506.csv', '1719965077330988.csv', '1719965077322426.csv', '1719965077324080.csv', '1719965077330803.csv', '1719965077326250.csv', '1719965077324490.csv', '1719965077323112.csv', '1719965077331264.csv', '1719965077323714.csv', '1719965077330543.csv', '1719965077322964.csv', '1719965077329399.csv', '1719965077324285.csv', '1719965077329038.csv', '1719965077321470.csv', '1719965077330226.csv', '1719965077330583.csv', '1719965077324051.csv', '1719965077330024.csv', '1719965077326120.csv', '1719965077322391.csv', '1719965077322018.csv', '1719965077329165.csv', '1719965077330834.csv', '1719965077330968.csv', '1719965077322606.csv', '1719965077326306.csv', '1719965077323097.csv', '1719965077323478.csv', '1719965077329196.csv', '1719965077329816.csv', '1719965077321279.csv', '1719965077324315.csv', '1719965077323650.csv', '1719965077329341.csv', '1719965077326066.csv', '1719965077331485.csv', '1719965077322638.csv', '1719965077329779.csv', '1719965077321443.csv', '1719965077322177.csv', '1719965077323533.csv', '1719965077329220.csv', '1719965077321898.csv', '1719965077321873.csv', '1719965077330942.csv', '1719965077326098.csv', '1719965077323686.csv', '1719965077323309.csv', '1719965077323447.csv', '1719965077330749.csv', '1719965077331457.csv', '1719965077329998.csv', '1719965077323251.csv', '1719965077324259.csv', '1719965077324517.csv', '1719965077322827.csv', '1719965077321731.csv', '1719965077324107.csv', '1719965077322762.csv', '1719965077330414.csv', '1719965077322206.csv', '1719965077322574.csv', '1719965077330616.csv', '1719965077324139.csv', '1719965077331534.csv', '1719965077323078.csv', '1719965077321647.csv', '1719965077321493.csv', '1719965077329965.csv', '1719965077323333.csv', '1719965077329876.csv', '1719965077330314.csv', '1719965077326172.csv', '1719965077330062.csv', '1719965077323591.csv', '1719965077321379.csv', '1719965077322659.csv', '1719965077329903.csv', '1719965077331369.csv', '1719965077331341.csv', '1719965077323619.csv', '1719965077330881.csv', '1719965077322077.csv', '1719965077322936.csv', '1719965077324438.csv', '1719965077329120.csv', '1719965077324404.csv', '1719965077323419.csv', '1719965077330115.csv', '1719965077330288.csv', '1719965077323223.csv', '1719965077322129.csv', '1719965077322672.csv', '1719965077330262.csv', '1719965077321409.csv', '1719965077321179.csv', '1719965077331430.csv', '1719965077322458.csv', '1719965077330666.csv', '1719965077321828.csv', '1719965077331178.csv', '1719965077321342.csv', '1719965077322688.csv', '1719965077330139.csv', '1719965077324164.csv', '1719965077328986.csv', '1719965077324602.csv', '1719965077322298.csv', '1719965077324372.csv', '1719965077321793.csv', '1719965077321988.csv', '1719965077329278.csv', '1719965077326361.csv', '1719965077323557.csv', '1719965077331153.csv', '1719965077323740.csv', '1719965077329251.csv', '1719965077323387.csv']

In [10]:
folder = 'data/quorumsims_test_small/train/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv')]
# fileNames = []
# siteConv = []
# timeConv = []
# siteQuals = []
# sitePoses = []
# numAg = []
submeta = pd.DataFrame([],columns=meta.columns)

for file in files:
    row = meta.loc[meta.file_name==file].values
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # fileNames.append(row.file_name)
    # siteConv.append(row.site_converged)
    # timeConv.append(row.time_converged)
    # siteQuals.append(row.site_qualities)
    # sitePoses.append(row.site_positions)
    # numAg.append(row.num_agents)
    # break
submeta.to_csv(folder+'metadata.csv')
# row
# [(fileName, site_conv, time_conv, entry, folder, folder_graph1, folder_graph2)

In [11]:
folder = 'data/quorumsims_test_small/'
folderto = 'data/quorumsims_test_small/test/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv') and file.startswith('1')]
for file in files:
    # if np.random.random() < 0.7:
    # print(file)
    shutil.move(folder+file, folderto+file)

In [12]:
folder = 'data/quorumsims_test_small/test/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv')]
# fileNames = []
# siteConv = []
# timeConv = []
# siteQuals = []
# sitePoses = []
# numAg = []
submeta = pd.DataFrame([],columns=meta.columns)

for file in files:
    row = meta.loc[meta.file_name==file].values
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # fileNames.append(row.file_name)
    # siteConv.append(row.site_converged)
    # timeConv.append(row.time_converged)
    # siteQuals.append(row.site_qualities)
    # sitePoses.append(row.site_positions)
    # numAg.append(row.num_agents)
    # break
submeta.to_csv(folder+'metadata.csv')
# row
# [(fileName, site_conv, time_conv, entry, folder, folder_graph1, folder_graph2)