In [55]:
import os 
import sys
import pandas as pd 
import numpy as np

folder = './random_data_test/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv')]
meta = pd.read_csv(folder+'metadata.csv')

In [56]:
submeta = pd.DataFrame([],columns=meta.columns)
submeta

Empty DataFrame
Columns: [file_name, site_qualities, site_positions, hub_position, num_agents, site_converged, time_converged, start_state, maxTime]
Index: []

In [57]:
import pdb
files.remove('metadata.csv')
for file in files[:-1]:
    
    row = meta.loc[meta.file_name==file].values
    # print(row, len(row[0]))
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # break
submeta

,file_name,site_qualities,site_positions,hub_position,num_agents,site_converged,time_converged,start_state,maxTime
0,1718673922208197.csv,"[0.858, 0.745]","[[200.0, 0.0], [-200.0, 0.0]]","[0.0, 0.0]",100,0.858,4601,"(('RECRUIT', 1), ('RECRUIT', 1), ('TRAVEL_HOME...",35000
1,1718673922225777.csv,"[0.858, 0.745]","[[150.0, 0.0], [-150.0, 0.0]]","[0.0, 0.0]",100,0.858,3240,"(('OBSERVE', None), ('TRAVEL_HOME_TO_OBSERVE',...",35000
2,1718673922226530.csv,"[0.858, 0.745]","[[150.0, 0.0], [-150.0, 0.0]]","[0.0, 0.0]",100,0.858,257,"(('EXPLORE', None), ('TRAVEL_HOME_TO_OBSERVE',...",35000
3,1718673922226524.csv,"[0.858, 0.745]","[[150.0, 0.0], [-150.0, 0.0]]","[0.0, 0.0]",100,0.858,296,"(('EXPLORE', None), ('TRAVEL_HOME_TO_OBSERVE',...",35000
4,1718673922203983.csv,"[0.858, 0.745]","[[200.0, 0.0], [-200.0, 0.0]]","[0.0, 0.0]",100,0.858,956,"(('TRAVEL_SITE', 0), ('EXPLORE', None), ('EXPL...",35000
...,...,...,...,...,...,...,...,...,...
722,1718673922207242.csv,"[0.858, 0.745]","[[200.0, 0.0], [-200.0, 0.0]]","[0.0, 0.0]",100,0.858,601,"(('TRAVEL_SITE', 0), ('OBSERVE', None), ('TRAV...",35000
723,1718673922225961.csv,"[0.858, 0.745]","[[150.0, 0.0], [-150.0, 0.0]]","[0.0, 0.0]",100,0.858,1,"(('TRAVEL_SITE', 0), ('RECRUIT', 0), ('RECRUIT...",35000
724,1718673922228262.csv,"[0.983, 0.929]","[[100.0, 0.0], [-100.0, 0.0]]","[0.0, 0.0]",100,0.929,46,"(('TRAVEL_SITE', 1), ('EXPLORE', None), ('TRAV...",35000
725,1718673922225008.csv,"[0.858, 0.745]","[[200.0, 0.0], [-200.0, 0.0]]","[0.0, 0.0]",100,0.858,4477,"(('ASSESS', 1), ('TRAVEL_SITE', 1), ('TRAVEL_S...",35000
726,1718673922203965.csv,"[0.858, 0.745]","[[200.0, 0.0], [-200.0, 0.0]]","[0.0, 0.0]",100,0.858,855,"(('TRAVEL_SITE', 0), ('EXPLORE', None), ('EXPL...",35000

In [58]:
from ast import literal_eval
submeta.site_qualities=submeta.site_qualities.apply(literal_eval)
submeta.site_positions=submeta.site_positions.apply(literal_eval)
submeta.site_qualities=submeta.site_qualities.apply(lambda x: tuple(x))
submeta.site_positions=submeta.site_positions.apply(lambda x: tuple([tuple(a) for a in x]))

df = submeta.groupby(by=['site_qualities', 'site_positions', 'num_agents'], as_index=False).agg(lambda x: x.tolist())

In [59]:
df['numentries'] = df.maxTime.apply(lambda x: len(x))
df.numentries

0    333
1    303
2     91
Name: numentries, dtype: int64

In [60]:
files_to_save_one_graph = df.iloc[0]['file_name']

# import os 
# import shutil
# import numpy as np
# fold = '../final_experiments/allGraphs_train/'
# fold_new = '../final_experiments/allGraphs_test/'
# files = os.listdir(fold)
# for file in files[:-1]:
#     if np.random.random() > 0.7:
#         print(file)
#         shutil.move(fold+file, fold_new+file)

In [61]:
len(files_to_save_one_graph)

333

In [62]:
import shutil
for file in files_to_save_one_graph:
# try:
    shutil.copy(folder+file, 'onegraph_files/'+file)
    # except:
        # continue

In [63]:

for file in files_to_save_one_graph[:-1]:
    if np.random.random() < 0.7:
        # print(file)
        shutil.move('onegraph_files/'+file, 'onegraph_files/train/'+file)

In [67]:
folder = 'onegraph_files/train/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv')]
# fileNames = []
# siteConv = []
# timeConv = []
# siteQuals = []
# sitePoses = []
# numAg = []
submeta = pd.DataFrame([],columns=meta.columns)

for file in files:
    row = meta.loc[meta.file_name==file].values
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # fileNames.append(row.file_name)
    # siteConv.append(row.site_converged)
    # timeConv.append(row.time_converged)
    # siteQuals.append(row.site_qualities)
    # sitePoses.append(row.site_positions)
    # numAg.append(row.num_agents)
    # break
submeta.to_csv(folder+'metadata.csv')
# row
# [(fileName, site_conv, time_conv, entry, folder, folder_graph1, folder_graph2)

In [ ]:
folder = 'onegraph_files/test/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv')]
# fileNames = []
# siteConv = []
# timeConv = []
# siteQuals = []
# sitePoses = []
# numAg = []
submeta = pd.DataFrame([],columns=meta.columns)

for file in files:
    row = meta.loc[meta.file_name==file].values
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # fileNames.append(row.file_name)
    # siteConv.append(row.site_converged)
    # timeConv.append(row.time_converged)
    # siteQuals.append(row.site_qualities)
    # sitePoses.append(row.site_positions)
    # numAg.append(row.num_agents)
    # break
submeta.to_csv(folder+'metadata.csv')
# row
# [(fileName, site_conv, time_conv, entry, folder, folder_graph1, folder_graph2)