In [59]:
import os 
import sys
import pandas as pd 
import numpy as np

folder = './data/quorum_sims_70_30_split/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv') and file.startswith('1')]
meta = pd.read_csv(folder+'metadata.csv')

In [60]:
submeta = pd.DataFrame([],columns=meta.columns)
submeta

Empty DataFrame
Columns: [file_name, site_qualities, site_positions, hub_position, num_agents, site_converged, time_converged, start_state, maxTime]
Index: []

In [61]:
import pdb
# files.remove('metadata.csv')
for file in files:
    
    row = meta.loc[meta.file_name==file].values
    # print(row, len(row[0]))
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # break
submeta

,file_name,site_qualities,site_positions,hub_position,num_agents,site_converged,time_converged,start_state,maxTime
0,1720158810492470.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.584,2322,"(('OBSERVE', None), ('ASSESS', 0), ('ASSESS', ...",35000
1,1720158810509888.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.584,4015,"(('EXPLORE', None), ('RECRUIT', 3), ('RECRUIT'...",35000
2,1720158810518013.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.584,1492,"(('RECRUIT', 3), ('OBSERVE', None), ('ASSESS',...",35000
3,1720158810486161.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.542,2690,(),35000
4,1720158810521484.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.476,443,"(('OBSERVE', None), ('OBSERVE', None), ('RECRU...",35000
...,...,...,...,...,...,...,...,...,...
534,1720158810501229.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.584,7949,"(('OBSERVE', None), ('OBSERVE', None), ('OBSER...",35000
535,1720158810499500.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.584,7959,"(('RECRUIT', 1), ('OBSERVE', None), ('OBSERVE'...",35000
536,1720158810513611.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.542,2051,"(('EXPLORE', None), ('RECRUIT', 1), ('RECRUIT'...",35000
537,1720158810518744.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.584,14261,"(('EXPLORE', None), ('EXPLORE', None), ('RECRU...",35000
538,1720158810490518.csv,"[0.542, 0.476, 0.438, 0.584]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.584,3348,"(('OBSERVE', None), ('OBSERVE', None), ('OBSER...",35000

In [62]:
from ast import literal_eval
submeta.site_qualities=submeta.site_qualities.apply(literal_eval)
submeta.site_positions=submeta.site_positions.apply(literal_eval)
submeta.site_qualities=submeta.site_qualities.apply(lambda x: tuple(x))
submeta.site_positions=submeta.site_positions.apply(lambda x: tuple([tuple(a) for a in x]))

df = submeta.groupby(by=['site_qualities', 'site_positions', 'num_agents'], as_index=False).agg(lambda x: x.tolist())

In [63]:
df['numentries'] = df.maxTime.apply(lambda x: len(x))
df.numentries

0    539
Name: numentries, dtype: int64

In [64]:
files_to_save_one_graph = df.iloc[0]['file_name']

# import os 
# import shutil
# import numpy as np
# fold = '../final_experiments/allGraphs_train/'
# fold_new = '../final_experiments/allGraphs_test/'
# files = os.listdir(fold)
# for file in files[:-1]:
#     if np.random.random() > 0.7:
#         print(file)
#         shutil.move(fold+file, fold_new+file)

In [65]:
len(files_to_save_one_graph)

539

In [66]:
import shutil
# for file in files_to_save_one_graph:
# # try:
#     shutil.copy(folder+file, './data/quorumsims_fixed_otheragents/'+file)
#     # except:
#         # continue

In [67]:
print(files_to_save_one_graph)
for file in files_to_save_one_graph:
    if np.random.random() < 0.6:
        # print(file)
        shutil.move(folder+file, folder + 'train/'+file)

['1720158810492470.csv', '1720158810509888.csv', '1720158810518013.csv', '1720158810486161.csv', '1720158810521484.csv', '1720158810510856.csv', '1720158810520995.csv', '1720158810507279.csv', '1720158810514577.csv', '1720158810512660.csv', '1720158810508176.csv', '1720158810500258.csv', '1720158810522012.csv', '1720158810518629.csv', '1720158810519279.csv', '1720158810517526.csv', '1720158810520349.csv', '1720158810523866.csv', '1720158810498982.csv', '1720158810516177.csv', '1720158810515318.csv', '1720158810508822.csv', '1720158810519708.csv', '1720158810511585.csv', '1720158810523537.csv', '1720158810491346.csv', '1720158810510300.csv', '1720158810521861.csv', '1720158810519326.csv', '1720158810516029.csv', '1720158810502048.csv', '1720158810511961.csv', '1720158810522401.csv', '1720158810500688.csv', '1720158810516559.csv', '1720158810517848.csv', '1720158810517690.csv', '1720158810501780.csv', '1720158810503008.csv', '1720158810516377.csv', '1720158810502458.csv', '1720158810517733.csv', '1720158810521256.csv', '1720158810512307.csv', '1720158810492261.csv', '1720158810513970.csv', '1720158810513781.csv', '1720158810514978.csv', '1720158810514005.csv', '1720158810501408.csv', '1720158810491231.csv', '1720158810522951.csv', '1720158810511431.csv', '1720158810504014.csv', '1720158810516410.csv', '1720158810501742.csv', '1720158810505530.csv', '1720158810500460.csv', '1720158810513839.csv', '1720158810502713.csv', '1720158810517326.csv', '1720158810507848.csv', '1720158810492674.csv', '1720158810490659.csv', '1720158810490881.csv', '1720158810490117.csv', '1720158810517246.csv', '1720158810520398.csv', '1720158810521086.csv', '1720158810517291.csv', '1720158810514798.csv', '1720158810523647.csv', '1720158810505119.csv', '1720158810510272.csv', '1720158810518148.csv', '1720158810515691.csv', '1720158810500505.csv', '1720158810511352.csv', '1720158810499091.csv', '1720158810520004.csv', '1720158810507336.csv', '1720158810517125.csv', '1720158810520951.csv', '1720158810519493.csv', '1720158810511781.csv', '1720158810518996.csv', '1720158810485679.csv', '1720158810512539.csv', '1720158810492313.csv', '1720158810523902.csv', '1720158810489914.csv', '1720158810503620.csv', '1720158810515724.csv', '1720158810490060.csv', '1720158810512705.csv', '1720158810505292.csv', '1720158810522163.csv', '1720158810492878.csv', '1720158810507532.csv', '1720158810519917.csv', '1720158810515863.csv', '1720158810503556.csv', '1720158810511191.csv', '1720158810522201.csv', '1720158810489849.csv', '1720158810518836.csv', '1720158810490471.csv', '1720158810504238.csv', '1720158810503972.csv', '1720158810501181.csv', '1720158810499870.csv', '1720158810521523.csv', '1720158810519043.csv', '1720158810510701.csv', '1720158810518361.csv', '1720158810508748.csv', '1720158810517654.csv', '1720158810491196.csv', '1720158810499535.csv', '1720158810506573.csv', '1720158810514177.csv', '1720158810508511.csv', '1720158810505035.csv', '1720158810522475.csv', '1720158810512005.csv', '1720158810492177.csv', '1720158810514306.csv', '1720158810521418.csv', '1720158810491278.csv', '1720158810523384.csv', '1720158810511487.csv', '1720158810510570.csv', '1720158810500763.csv', '1720158810491907.csv', '1720158810514930.csv', '1720158810516699.csv', '1720158810507757.csv', '1720158810486249.csv', '1720158810499427.csv', '1720158810519555.csv', '1720158810503928.csv', '1720158810505418.csv', '1720158810510767.csv', '1720158810522851.csv', '1720158810515025.csv', '1720158810507810.csv', '1720158810510405.csv', '1720158810499235.csv', '1720158810521180.csv', '1720158810515580.csv', '1720158810501287.csv', '1720158810519635.csv', '1720158810516260.csv', '1720158810504664.csv', '1720158810511533.csv', '1720158810520739.csv', '1720158810513495.csv', '1720158810510836.csv', '1720158810490165.csv', '1720158810491051.csv', '1720158810503527.csv', '1720158810498934.csv', '1720158810515393.csv', '1720158810505625.csv', '1720158810516103.csv', '1720158810507224.csv', '1720158810515620.csv', '1720158810520857.csv', '1720158810514270.csv', '1720158810486060.csv', '1720158810514489.csv', '1720158810522891.csv', '1720158810508922.csv', '1720158810490992.csv', '1720158810515224.csv', '1720158810513645.csv', '1720158810519368.csv', '1720158810492367.csv', '1720158810513686.csv', '1720158810521634.csv', '1720158810498851.csv', '1720158810506738.csv', '1720158810503132.csv', '1720158810500407.csv', '1720158810490799.csv', '1720158810500215.csv', '1720158810505386.csv', '1720158810508852.csv', '1720158810521797.csv', '1720158810508463.csv', '1720158810515354.csv', '1720158810503244.csv', '1720158810516661.csv', '1720158810520463.csv', '1720158810489815.csv', '1720158810521755.csv', '1720158810514088.csv', '1720158810518103.csv', '1720158810523181.csv', '1720158810511133.csv', '1720158810519962.csv', '1720158810495031.csv', '1720158810519194.csv', '1720158810499958.csv', '1720158810517813.csv', '1720158810513320.csv', '1720158810500837.csv', '1720158810502775.csv', '1720158810506261.csv', '1720158810511053.csv', '1720158810491651.csv', '1720158810510373.csv', '1720158810489977.csv', '1720158810507419.csv', '1720158810510993.csv', '1720158810516460.csv', '1720158810499184.csv', '1720158810523829.csv', '1720158810518673.csv', '1720158810515431.csv', '1720158810501478.csv', '1720158810503284.csv', '1720158810491094.csv', '1720158810513929.csv', '1720158810507948.csv', '1720158810523140.csv', '1720158810502818.csv', '1720158810505804.csv', '1720158810521030.csv', '1720158810511859.csv', '1720158810505192.csv', '1720158810509970.csv', '1720158810490360.csv', '1720158810513727.csv', '1720158810505151.csv', '1720158810504918.csv', '1720158810519791.csv', '1720158810512820.csv', '1720158810490837.csv', '1720158810508887.csv', '1720158810521597.csv', '1720158810491526.csv', '1720158810513531.csv', '1720158810523223.csv', '1720158810516298.csv', '1720158810486112.csv', '1720158810502212.csv', '1720158810511246.csv', '1720158810508703.csv', '1720158810523009.csv', '1720158810511911.csv', '1720158810516924.csv', '1720158810501531.csv', '1720158810487026.csv', '1720158810513886.csv', '1720158810520294.csv', '1720158810508242.csv', '1720158810512583.csv', '1720158810515993.csv', '1720158810491311.csv', '1720158810501925.csv', '1720158810520069.csv', '1720158810521363.csv', '1720158810492750.csv', '1720158810502419.csv', '1720158810521559.csv', '1720158810502380.csv', '1720158810521217.csv', '1720158810514723.csv', '1720158810492546.csv', '1720158810485760.csv', '1720158810521968.csv', '1720158810517202.csv', '1720158810511698.csv', '1720158810506497.csv', '1720158810502632.csv', '1720158810512353.csv', '1720158810500596.csv', '1720158810522086.csv', '1720158810517029.csv', '1720158810504055.csv', '1720158810512794.csv', '1720158810522125.csv', '1720158810517613.csv', '1720158810523777.csv', '1720158810505954.csv', '1720158810522441.csv', '1720158810516069.csv', '1720158810513105.csv', '1720158810490232.csv', '1720158810511738.csv', '1720158810518907.csv', '1720158810506293.csv', '1720158810516527.csv', '1720158810499028.csv', '1720158810506132.csv', '1720158810490622.csv', '1720158810501649.csv', '1720158810501113.csv', '1720158810522047.csv', '1720158810506867.csv', '1720158810506456.csv', '1720158810506330.csv', '1720158810511664.csv', '1720158810486295.csv', '1720158810516876.csv', '1720158810512393.csv', '1720158810500032.csv', '1720158810502157.csv', '1720158810504526.csv', '1720158810517770.csv', '1720158810513270.csv', '1720158810506669.csv', '1720158810519749.csv', '1720158810505348.csv', '1720158810501890.csv', '1720158810504724.csv', '1720158810490958.csv', '1720158810518245.csv', '1720158810490757.csv', '1720158810512754.csv', '1720158810505228.csv', '1720158810522318.csv', '1720158810514669.csv', '1720158810504320.csv', '1720158810486337.csv', '1720158810503477.csv', '1720158810492408.csv', '1720158810491129.csv', '1720158810507639.csv', '1720158810489772.csv', '1720158810490592.csv', '1720158810491698.csv', '1720158810515765.csv', '1720158810510153.csv', '1720158810523572.csv', '1720158810504867.csv', '1720158810515942.csv', '1720158810510190.csv', '1720158810511311.csv', '1720158810508132.csv', '1720158810507017.csv', '1720158810508318.csv', '1720158810523610.csv', '1720158810522240.csv', '1720158810504286.csv', '1720158810490430.csv', '1720158810499372.csv', '1720158810517577.csv', '1720158810503099.csv', '1720158810508669.csv', '1720158810510032.csv', '1720158810512625.csv', '1720158810518297.csv', '1720158810512976.csv', '1720158810518532.csv', '1720158810503674.csv', '1720158810520907.csv', '1720158810520536.csv', '1720158810514863.csv', '1720158810499574.csv', '1720158810505991.csv', '1720158810490550.csv', '1720158810505761.csv', '1720158810507162.csv', '1720158810500169.csv', '1720158810507606.csv', '1720158810506530.csv', '1720158810504482.csv', '1720158810492621.csv', '1720158810503886.csv', '1720158810500357.csv', '1720158810510811.csv', '1720158810503716.csv', '1720158810499827.csv', '1720158810504092.csv', '1720158810516496.csv', '1720158810513061.csv', '1720158810514040.csv', '1720158810522280.csv', '1720158810509944.csv', '1720158810490397.csv', '1720158810522531.csv', '1720158810492581.csv', '1720158810510233.csv', '1720158810509992.csv', '1720158810501699.csv', '1720158810501855.csv', '1720158810518486.csv', '1720158810499615.csv', '1720158810503059.csv', '1720158810507571.csv', '1720158810506928.csv', '1720158810508093.csv', '1720158810504130.csv', '1720158810502555.csv', '1720158810517170.csv', '1720158810499991.csv', '1720158810491473.csv', '1720158810502964.csv', '1720158810500801.csv', '1720158810508209.csv', '1720158810516779.csv', '1720158810501577.csv', '1720158810500872.csv', '1720158810492109.csv', '1720158810522806.csv', '1720158810513365.csv', '1720158810508037.csv', '1720158810504194.csv', '1720158810512906.csv', '1720158810515106.csv', '1720158810522755.csv', '1720158810520624.csv', '1720158810502491.csv', '1720158810517922.csv', '1720158810490326.csv', '1720158810499464.csv', '1720158810505881.csv', '1720158810491979.csv', '1720158810515463.csv', '1720158810501358.csv', '1720158810499303.csv', '1720158810516630.csv', '1720158810486009.csv', '1720158810516340.csv', '1720158810503759.csv', '1720158810508787.csv', '1720158810504803.csv', '1720158810507463.csv', '1720158810515067.csv', '1720158810505260.csv', '1720158810504630.csv', '1720158810508591.csv', '1720158810491824.csv', '1720158810503375.csv', '1720158810491165.csv', '1720158810520586.csv', '1720158810504356.csv', '1720158810510337.csv', '1720158810486369.csv', '1720158810505074.csv', '1720158810491601.csv', '1720158810504395.csv', '1720158810490286.csv', '1720158810505921.csv', '1720158810518794.csv', '1720158810510647.csv', '1720158810517882.csv', '1720158810501038.csv', '1720158810485462.csv', '1720158810501004.csv', '1720158810519878.csv', '1720158810513399.csv', '1720158810519844.csv', '1720158810506970.csv', '1720158810514233.csv', '1720158810502323.csv', '1720158810488998.csv', '1720158810520141.csv', '1720158810504961.csv', '1720158810516140.csv', '1720158810520431.csv', '1720158810508381.csv', '1720158810523676.csv', '1720158810518186.csv', '1720158810521707.csv', '1720158810505840.csv', '1720158810486208.csv', '1720158810505667.csv', '1720158810508425.csv', '1720158810506420.csv', '1720158810501818.csv', '1720158810506187.csv', '1720158810518434.csv', '1720158810512119.csv', '1720158810520197.csv', '1720158810503835.csv', '1720158810506030.csv', '1720158810502524.csv', '1720158810507110.csv', '1720158810508551.csv', '1720158810510444.csv', '1720158810505717.csv', '1720158810516964.csv', '1720158810522357.csv', '1720158810499066.csv', '1720158810502252.csv', '1720158810523277.csv', '1720158810506785.csv', '1720158810523471.csv', '1720158810513015.csv', '1720158810511819.csv', '1720158810506381.csv', '1720158810500097.csv', '1720158810485937.csv', '1720158810504583.csv', '1720158810500726.csv', '1720158810500295.csv', '1720158810521298.csv', '1720158810492046.csv', '1720158810513570.csv', '1720158810513202.csv', '1720158810516597.csv', '1720158810521139.csv', '1720158810523048.csv', '1720158810499271.csv', '1720158810506223.csv', '1720158810500652.csv', '1720158810515275.csv', '1720158810503167.csv', '1720158810490914.csv', '1720158810508634.csv', '1720158810511167.csv', '1720158810511629.csv', '1720158810512446.csv', '1720158810500903.csv', '1720158810502873.csv', '1720158810516812.csv', '1720158810489698.csv', '1720158810492509.csv', '1720158810512862.csv', '1720158810504999.csv', '1720158810515658.csv', '1720158810507499.csv', '1720158810501956.csv', '1720158810499919.csv', '1720158810514340.csv', '1720158810501995.csv', '1720158810514432.csv', '1720158810519116.csv', '1720158810491376.csv', '1720158810516219.csv', '1720158810510481.csv', '1720158810501229.csv', '1720158810499500.csv', '1720158810513611.csv', '1720158810518744.csv', '1720158810490518.csv']

In [68]:
folder_t = folder + 'train/'
files = os.listdir(folder_t)
files = [file for file in files if file.endswith('.csv')]
# fileNames = []
# siteConv = []
# timeConv = []
# siteQuals = []
# sitePoses = []
# numAg = []
submeta = pd.DataFrame([],columns=meta.columns)

for file in files:
    row = meta.loc[meta.file_name==file].values
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # fileNames.append(row.file_name)
    # siteConv.append(row.site_converged)
    # timeConv.append(row.time_converged)
    # siteQuals.append(row.site_qualities)
    # sitePoses.append(row.site_positions)
    # numAg.append(row.num_agents)
    # break
submeta.to_csv(folder_t+'metadata.csv')
# row
# [(fileName, site_conv, time_conv, entry, folder, folder_graph1, folder_graph2)

In [69]:
# folder = 'data/quorum_sims_all/'
print(folder)
folderto = folder + 'test/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv') and file.startswith('1')]
for file in files:
    # if np.random.random() < 0.7:
    # print(file)
    shutil.move(folder+file, folderto+file)

./data/quorum_sims_70_30_split/

In [70]:
folder_test = folder + 'test/'
files = os.listdir(folder_test)
files = [file for file in files if file.endswith('.csv')]
# fileNames = []
# siteConv = []
# timeConv = []
# siteQuals = []
# sitePoses = []
# numAg = []
submeta = pd.DataFrame([],columns=meta.columns)

for file in files:
    row = meta.loc[meta.file_name==file].values
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # fileNames.append(row.file_name)
    # siteConv.append(row.site_converged)
    # timeConv.append(row.time_converged)
    # siteQuals.append(row.site_qualities)
    # sitePoses.append(row.site_positions)
    # numAg.append(row.num_agents)
    # break
submeta.to_csv(folder_test+'metadata.csv')
# row
# [(fileName, site_conv, time_conv, entry, folder, folder_graph1, folder_graph2)