In [92]:
import os 
import sys
import pandas as pd 
import numpy as np

folder = './data/multirunsims/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv') and file.startswith('1')]
meta = pd.read_csv(folder+'metadata.csv')

In [93]:
submeta = pd.DataFrame([],columns=meta.columns)
submeta

Empty DataFrame
Columns: [file_name, site_qualities, site_positions, hub_position, num_agents, site_converged, time_converged, start_state, maxTime, timelimitsave]
Index: []

In [94]:
import pdb
# files.remove('metadata.csv')
for file in files:
    
    row = meta.loc[meta.file_name==file].values
    # print(row, len(row[0]))
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # break
submeta

,file_name,site_qualities,site_positions,hub_position,num_agents,site_converged,time_converged,start_state,maxTime,timelimitsave
0,1721021195573711.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,84,"(('OBSERVE', None), ('TRAVEL_SITE', 2), ('EXPL...",20000,20000
1,1721021195752015.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,9,"(('RECRUIT', 2), ('TRAVEL_SITE', 2), ('EXPLORE...",20000,20000
2,1721021195743118.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,104,"(('RECRUIT', 2), ('TRAVEL_SITE', 2), ('EXPLORE...",20000,20000
3,1721021195559846.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,92,"(('OBSERVE', None), ('OBSERVE', None), ('OBSER...",20000,20000
4,1721021195594808.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,204,"(('TRAVEL_SITE', 2), ('ASSESS', 2), ('EXPLORE'...",20000,20000
...,...,...,...,...,...,...,...,...,...,...
3029,1721021195594187.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,165,"(('TRAVEL_SITE', 2), ('ASSESS', 2), ('EXPLORE'...",20000,20000
3030,1721021195560774.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,134,"(('OBSERVE', None), ('OBSERVE', None), ('OBSER...",20000,20000
3031,1721021195562163.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,84,"(('OBSERVE', None), ('OBSERVE', None), ('OBSER...",20000,20000
3032,1721021195735929.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,89,"(('TRAVEL_HOME_TO_RECRUIT', 2), ('TRAVEL_HOME_...",20000,20000
3033,1721021195743667.csv,"[0.156, 0.906, 0.87, 0.95]","[[150.0, 0.0], [0.0, 150.0], [-150.0, 0.0], [-...","[0.0, 0.0]",10,0.87,121,"(('RECRUIT', 2), ('TRAVEL_SITE', 2), ('EXPLORE...",20000,20000

In [95]:
from ast import literal_eval
submeta.site_qualities=submeta.site_qualities.apply(literal_eval)
submeta.site_positions=submeta.site_positions.apply(literal_eval)
submeta.site_qualities=submeta.site_qualities.apply(lambda x: tuple(x))
submeta.site_positions=submeta.site_positions.apply(lambda x: tuple([tuple(a) for a in x]))

df = submeta.groupby(by=['site_qualities', 'site_positions', 'num_agents'], as_index=False).agg(lambda x: x.tolist())

In [96]:
df['numentries'] = df.maxTime.apply(lambda x: len(x))
df.numentries

0    3032
1       1
2       1
Name: numentries, dtype: int64

In [104]:
df

,site_qualities,site_positions,num_agents,file_name,hub_position,site_converged,time_converged,start_state,maxTime,timelimitsave,numentries
0,"(0.156, 0.906, 0.87, 0.95)","((150.0, 0.0), (0.0, 150.0), (-150.0, 0.0), (-...",10,"[1721021195573711.csv, 1721021195752015.csv, 1...","[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0...","[0.87, 0.87, 0.87, 0.87, 0.87, 0.87, 0.87, 0.8...","[84, 9, 104, 92, 204, 139, 59, 23, 111, 366, 1...","[(('OBSERVE', None), ('TRAVEL_SITE', 2), ('EXP...","[20000, 20000, 20000, 20000, 20000, 20000, 200...","[20000, 20000, 20000, 20000, 20000, 20000, 200...",3032
1,"(0.573, 0.046, 0.039, 0.639)","((150.0, 0.0), (0.0, 150.0), (-150.0, 0.0), (-...",10,[1721021111795770.csv],"[[0.0, 0.0]]",[0.573],[3421],[()],[35000],[20000],1
2,"(0.737, 0.145, 0.831, 0.223)","((150.0, 0.0), (0.0, 150.0), (-150.0, 0.0), (-...",10,[1721021168199677.csv],"[[0.0, 0.0]]",[0.831],[784],[()],[35000],[20000],1

In [97]:
files_to_save_one_graph = df.iloc[0]['file_name']

# import os 
# import shutil
# import numpy as np
# fold = '../final_experiments/allGraphs_train/'
# fold_new = '../final_experiments/allGraphs_test/'
# files = os.listdir(fold)
# for file in files[:-1]:
#     if np.random.random() > 0.7:
#         print(file)
#         shutil.move(fold+file, fold_new+file)

In [98]:
len(files_to_save_one_graph)

3032

In [99]:
import shutil
# for file in files_to_save_one_graph:
# # try:
#     shutil.copy(folder+file, './data/quorumsims_fixed_otheragents/'+file)
#     # except:
#         # continue

In [100]:
print(files_to_save_one_graph)
for file in files_to_save_one_graph:
    if np.random.random() <= 0.7:
        # print(file)
        shutil.move(folder+file, folder + 'train/'+file)

['1721021195573711.csv', '1721021195752015.csv', '1721021195743118.csv', '1721021195559846.csv', '1721021195594808.csv', '1721021195571884.csv', '1721021195589681.csv', '1721021195732911.csv', '1721021195709987.csv', '1721021195541953.csv', '1721021195573739.csv', '1721021195574056.csv', '1721021195547477.csv', '1721021195722531.csv', '1721021195596004.csv', '1721021195584366.csv', '1721021195542527.csv', '1721021195734192.csv', '1721021195751078.csv', '1721021195574268.csv', '1721021195591582.csv', '1721021195581791.csv', '1721021195735298.csv', '1721021195570768.csv', '1721021195722914.csv', '1721021195741531.csv', '1721021195561895.csv', '1721021195577991.csv', '1721021195734810.csv', '1721021195749179.csv', '1721021195734151.csv', '1721021195745970.csv', '1721021195570967.csv', '1721021195758921.csv', '1721021195756918.csv', '1721021195759395.csv', '1721021195549102.csv', '1721021195551981.csv', '1721021195738743.csv', '1721021195533043.csv', '1721021195758896.csv', '1721021195585497.csv', '1721021195719160.csv', '1721021195744273.csv', '1721021195591390.csv', '1721021195744515.csv', '1721021195740773.csv', '1721021195738186.csv', '1721021195757541.csv', '1721021195601061.csv', '1721021195728381.csv', '1721021195521309.csv', '1721021195545843.csv', '1721021195725128.csv', '1721021195724236.csv', '1721021195595121.csv', '1721021195729712.csv', '1721021195546379.csv', '1721021195542679.csv', '1721021195724544.csv', '1721021195558153.csv', '1721021195522827.csv', '1721021195741486.csv', '1721021195743291.csv', '1721021195552456.csv', '1721021195747791.csv', '1721021195710805.csv', '1721021195756688.csv', '1721021195550533.csv', '1721021195530990.csv', '1721021195722486.csv', '1721021195751468.csv', '1721021195568245.csv', '1721021195719404.csv', '1721021195569167.csv', '1721021195743044.csv', '1721021195717373.csv', '1721021195555107.csv', '1721021195716086.csv', '1721021195712586.csv', '1721021195734233.csv', '1721021195722337.csv', '1721021195549512.csv', '1721021195739059.csv', '1721021195714875.csv', '1721021195592470.csv', '1721021195737712.csv', '1721021195751497.csv', '1721021195552640.csv', '1721021195584560.csv', '1721021195582676.csv', '1721021195733207.csv', '1721021195568293.csv', '1721021195710384.csv', '1721021195713855.csv', '1721021195743904.csv', '1721021195596159.csv', '1721021195736343.csv', '1721021195583232.csv', '1721021195729277.csv', '1721021195748845.csv', '1721021195547502.csv', '1721021195557077.csv', '1721021195556382.csv', '1721021195528648.csv', '1721021195529556.csv', '1721021195710409.csv', '1721021195748662.csv', '1721021195717400.csv', '1721021195544962.csv', '1721021195712550.csv', '1721021195740570.csv', '1721021195595493.csv', '1721021195523047.csv', '1721021195597284.csv', '1721021195753518.csv', '1721021195563477.csv', '1721021195756306.csv', '1721021195742373.csv', '1721021195753929.csv', '1721021195597079.csv', '1721021195546436.csv', '1721021195718294.csv', '1721021195585469.csv', '1721021195573499.csv', '1721021195529973.csv', '1721021195568091.csv', '1721021195591420.csv', '1721021195747974.csv', '1721021195551162.csv', '1721021195714479.csv', '1721021195743521.csv', '1721021195715001.csv', '1721021195551823.csv', '1721021195738839.csv', '1721021195547927.csv', '1721021195556802.csv', '1721021195722849.csv', '1721021195759237.csv', '1721021195563932.csv', '1721021195594404.csv', '1721021195548209.csv', '1721021195712801.csv', '1721021195739448.csv', '1721021195549665.csv', '1721021195531906.csv', '1721021195592049.csv', '1721021195739306.csv', '1721021195547660.csv', '1721021195597131.csv', '1721021195588777.csv', '1721021195548235.csv', '1721021195751910.csv', '1721021195722732.csv', '1721021195600587.csv', '1721021195724425.csv', '1721021195569589.csv', '1721021195751051.csv', '1721021195728592.csv', '1721021195751723.csv', '1721021195551957.csv', '1721021195552286.csv', '1721021195533122.csv', '1721021195597680.csv', '1721021195595097.csv', '1721021195736784.csv', '1721021195585284.csv', '1721021195578447.csv', '1721021195567567.csv', '1721021195532228.csv', '1721021195724169.csv', '1721021195559106.csv', '1721021195751290.csv', '1721021195519244.csv', '1721021195529387.csv', '1721021195714900.csv', '1721021195577589.csv', '1721021195557881.csv', '1721021195736579.csv', '1721021195549301.csv', '1721021195737667.csv', '1721021195572397.csv', '1721021195600791.csv', '1721021195545513.csv', '1721021195530826.csv', '1721021195728948.csv', '1721021195737868.csv', '1721021195530601.csv', '1721021195578679.csv', '1721021195715405.csv', '1721021195532770.csv', '1721021195574725.csv', '1721021195531279.csv', '1721021195751521.csv', '1721021195717574.csv', '1721021195596950.csv', '1721021195756266.csv', '1721021195566309.csv', '1721021195754317.csv', '1721021195531245.csv', '1721021195598969.csv', '1721021195533322.csv', '1721021195583387.csv', '1721021195541978.csv', '1721021195716132.csv', '1721021195744112.csv', '1721021195719229.csv', '1721021195530171.csv', '1721021195747355.csv', '1721021195560746.csv', '1721021195581235.csv', '1721021195543160.csv', '1721021195521097.csv', '1721021195557101.csv', '1721021195582728.csv', '1721021195716697.csv', '1721021195545263.csv', '1721021195729301.csv', '1721021195575388.csv', '1721021195556551.csv', '1721021195590304.csv', '1721021195592261.csv', '1721021195584403.csv', '1721021195592936.csv', '1721021195583185.csv', '1721021195742775.csv', '1721021195714533.csv', '1721021195744304.csv', '1721021195720682.csv', '1721021195568130.csv', '1721021195575607.csv', '1721021195576326.csv', '1721021195715177.csv', '1721021195753122.csv', '1721021195572626.csv', '1721021195579767.csv', '1721021195753877.csv', '1721021195591230.csv', '1721021195729665.csv', '1721021195592711.csv', '1721021195584173.csv', '1721021195752599.csv', '1721021195734608.csv', '1721021195757393.csv', '1721021195725842.csv', '1721021195742173.csv', '1721021195722687.csv', '1721021195556182.csv', '1721021195563139.csv', '1721021195575983.csv', '1721021195574323.csv', '1721021195734967.csv', '1721021195588832.csv', '1721021195712778.csv', '1721021195548343.csv', '1721021195715942.csv', '1721021195545673.csv', '1721021195590072.csv', '1721021195559272.csv', '1721021195721365.csv', '1721021195542652.csv', '1721021195596365.csv', '1721021195588629.csv', '1721021195732696.csv', '1721021195749542.csv', '1721021195578733.csv', '1721021195732866.csv', '1721021195566257.csv', '1721021195561538.csv', '1721021195724976.csv', '1721021195548814.csv', '1721021195549539.csv', '1721021195551376.csv', '1721021195551404.csv', '1721021195590258.csv', '1721021195735884.csv', '1721021195572593.csv', '1721021195733563.csv', '1721021195596601.csv', '1721021195743090.csv', '1721021195548169.csv', '1721021195738344.csv', '1721021195521861.csv', '1721021195571931.csv', '1721021195549276.csv', '1721021195546145.csv', '1721021195574849.csv', '1721021195562795.csv', '1721021195578915.csv', '1721021195592314.csv', '1721021195570391.csv', '1721021195567821.csv', '1721021195744932.csv', '1721021195555663.csv', '1721021195565978.csv', '1721021195560800.csv', '1721021195542479.csv', '1721021195734557.csv', '1721021195581426.csv', '1721021195556418.csv', '1721021195569830.csv', '1721021195585898.csv', '1721021195757972.csv', '1721021195585126.csv', '1721021195557935.csv', '1721021195532175.csv', '1721021195744701.csv', '1721021195754512.csv', '1721021195734580.csv', '1721021195742416.csv', '1721021195559930.csv', '1721021195523291.csv', '1721021195597052.csv', '1721021195579835.csv', '1721021195736156.csv', '1721021195710191.csv', '1721021195734027.csv', '1721021195563879.csv', '1721021195745621.csv', '1721021195752349.csv', '1721021195567438.csv', '1721021195528307.csv', '1721021195710634.csv', '1721021195545869.csv', '1721021195548395.csv', '1721021195746300.csv', '1721021195574478.csv', '1721021195523246.csv', '1721021195531642.csv', '1721021195578524.csv', '1721021195550451.csv', '1721021195721204.csv', '1721021195740822.csv', '1721021195556034.csv', '1721021195574295.csv', '1721021195592076.csv', '1721021195551015.csv', '1721021195583153.csv', '1721021195550479.csv', '1721021195582259.csv', '1721021195549896.csv', '1721021195737328.csv', '1721021195572800.csv', '1721021195753651.csv', '1721021195574530.csv', '1721021195575160.csv', '1721021195752573.csv', '1721021195563064.csv', '1721021195584199.csv', '1721021195749153.csv', '1721021195733833.csv', '1721021195522992.csv', '1721021195754116.csv', '1721021195716872.csv', '1721021195728744.csv', '1721021195723611.csv', '1721021195586215.csv', '1721021195737102.csv', '1721021195738231.csv', '1721021195733370.csv', '1721021195523871.csv', '1721021195720442.csv', '1721021195550109.csv', '1721021195710581.csv', '1721021195556578.csv', '1721021195722241.csv', '1721021195757635.csv', '1721021195748715.csv', '1721021195745225.csv', '1721021195752981.csv', '1721021195728793.csv', '1721021195758274.csv', '1721021195544829.csv', '1721021195575362.csv', '1721021195581585.csv', '1721021195566478.csv', '1721021195593181.csv', '1721021195577561.csv', '1721021195575410.csv', '1721021195746076.csv', '1721021195569001.csv', '1721021195571128.csv', '1721021195572421.csv', '1721021195562626.csv', '1721021195522202.csv', '1721021195751240.csv', '1721021195548965.csv', '1721021195576135.csv', '1721021195588599.csv', '1721021195724191.csv', '1721021195722286.csv', '1721021195548781.csv', '1721021195711658.csv', '1721021195561313.csv', '1721021195752775.csv', '1721021195743693.csv', '1721021195567951.csv', '1721021195542253.csv', '1721021195757194.csv', '1721021195739103.csv', '1721021195736224.csv', '1721021195545925.csv', '1721021195556781.csv', '1721021195719012.csv', '1721021195558784.csv', '1721021195714250.csv', '1721021195560569.csv', '1721021195523322.csv', '1721021195759422.csv', '1721021195710977.csv', '1721021195556756.csv', '1721021195586761.csv', '1721021195588994.csv', '1721021195583619.csv', '1721021195737462.csv', '1721021195735275.csv', '1721021195725066.csv', '1721021195739329.csv', '1721021195730457.csv', '1721021195555277.csv', '1721021195713311.csv', '1721021195745157.csv', '1721021195747998.csv', '1721021195751644.csv', '1721021195713463.csv', '1721021195579170.csv', '1721021195758674.csv', '1721021195542858.csv', '1721021195714324.csv', '1721021195592847.csv', '1721021195756117.csv', '1721021195558182.csv', '1721021195531134.csv', '1721021195743268.csv', '1721021195715748.csv', '1721021195742610.csv', '1721021195726382.csv', '1721021195733764.csv', '1721021195738625.csv', '1721021195723563.csv', '1721021195745180.csv', '1721021195562593.csv', '1721021195729066.csv', '1721021195542119.csv', '1721021195726427.csv', '1721021195739261.csv', '1721021195593230.csv', '1721021195543561.csv', '1721021195753906.csv', '1721021195758462.csv', '1721021195559908.csv', '1721021195558394.csv', '1721021195587090.csv', '1721021195735856.csv', '1721021195736393.csv', '1721021195710432.csv', '1721021195591180.csv', '1721021195759032.csv', '1721021195566285.csv', '1721021195573850.csv', '1721021195560192.csv', '1721021195519337.csv', '1721021195555883.csv', '1721021195556352.csv', '1721021195528698.csv', '1721021195560838.csv', '1721021195562975.csv', '1721021195585650.csv', '1721021195724032.csv', '1721021195732650.csv', '1721021195726142.csv', '1721021195588375.csv', '1721021195732889.csv', '1721021195571908.csv', '1721021195541607.csv', '1721021195588407.csv', '1721021195724999.csv', '1721021195548623.csv', '1721021195591618.csv', '1721021195727506.csv', '1721021195716903.csv', '1721021195542326.csv', '1721021195600813.csv', '1721021195752199.csv', '1721021195564487.csv', '1721021195757793.csv', '1721021195590512.csv', '1721021195752833.csv', '1721021195542454.csv', '1721021195716042.csv', '1721021195596822.csv', '1721021195752172.csv', '1721021195713648.csv', '1721021195600620.csv', '1721021195593782.csv', '1721021195711711.csv', '1721021195753244.csv', '1721021195757022.csv', '1721021195518941.csv', '1721021195749208.csv', '1721021195751321.csv', '1721021195530767.csv', '1721021195745803.csv', '1721021195726354.csv', '1721021195733981.csv', '1721021195570828.csv', '1721021195742822.csv', '1721021195594576.csv', '1721021195737503.csv', '1721021195594210.csv', '1721021195754926.csv', '1721021195564849.csv', '1721021195754715.csv', '1721021195747769.csv', '1721021195587287.csv', '1721021195724594.csv', '1721021195753046.csv', '1721021195532400.csv', '1721021195529034.csv', '1721021195550291.csv', '1721021195552486.csv', '1721021195581999.csv', '1721021195521285.csv', '1721021195559316.csv', '1721021195737305.csv', '1721021195586012.csv', '1721021195581769.csv', '1721021195522968.csv', '1721021195572187.csv', '1721021195723402.csv', '1721021195586953.csv', '1721021195712634.csv', '1721021195740614.csv', '1721021195718319.csv', '1721021195722091.csv', '1721021195756062.csv', '1721021195569216.csv', '1721021195745750.csv', '1721021195589484.csv', '1721021195553820.csv', '1721021195743447.csv', '1721021195758701.csv', '1721021195742995.csv', '1721021195739499.csv', '1721021195738787.csv', '1721021195585043.csv', '1721021195558236.csv', '1721021195736557.csv', '1721021195717599.csv', '1721021195728769.csv', '1721021195759190.csv', '1721021195586238.csv', '1721021195580891.csv', '1721021195578864.csv', '1721021195709957.csv', '1721021195586562.csv', '1721021195567788.csv', '1721021195559666.csv', '1721021195523121.csv', '1721021195550871.csv', '1721021195750605.csv', '1721021195744670.csv', '1721021195544804.csv', '1721021195734397.csv', '1721021195529418.csv', '1721021195559699.csv', '1721021195532038.csv', '1721021195718899.csv', '1721021195729488.csv', '1721021195593812.csv', '1721021195742559.csv', '1721021195753440.csv', '1721021195713702.csv', '1721021195523645.csv', '1721021195521052.csv', '1721021195720486.csv', '1721021195715429.csv', '1721021195710237.csv', '1721021195742217.csv', '1721021195571842.csv', '1721021195738550.csv', '1721021195582074.csv', '1721021195549463.csv', '1721021195734418.csv', '1721021195564283.csv', '1721021195589653.csv', '1721021195600971.csv', '1721021195732727.csv', '1721021195734356.csv', '1721021195598776.csv', '1721021195712391.csv', '1721021195726020.csv', '1721021195559880.csv', '1721021195590458.csv', '1721021195555062.csv', '1721021195713925.csv', '1721021195547300.csv', '1721021195519095.csv', '1721021195736964.csv', '1721021195711303.csv', '1721021195566133.csv', '1721021195745020.csv', '1721021195586789.csv', '1721021195746273.csv', '1721021195578331.csv', '1721021195560218.csv', '1721021195548594.csv', '1721021195563711.csv', '1721021195742940.csv', '1721021195563088.csv', '1721021195596571.csv', '1721021195727666.csv', '1721021195738020.csv', '1721021195584613.csv', '1721021195559466.csv', '1721021195726550.csv', '1721021195739470.csv', '1721021195523490.csv', '1721021195720653.csv', '1721021195741326.csv', '1721021195720914.csv', '1721021195523269.csv', '1721021195554793.csv', '1721021195597900.csv', '1721021195543589.csv', '1721021195595871.csv', '1721021195530567.csv', '1721021195754071.csv', '1721021195714455.csv', '1721021195757578.csv', '1721021195595681.csv', '1721021195554977.csv', '1721021195563856.csv', '1721021195599044.csv', '1721021195560387.csv', '1721021195584015.csv', '1721021195580273.csv', '1721021195745829.csv', '1721021195586158.csv', '1721021195737529.csv', '1721021195720727.csv', '1721021195541836.csv', '1721021195564320.csv', '1721021195756458.csv', '1721021195751445.csv', '1721021195740548.csv', '1721021195579365.csv', '1721021195743069.csv', '1721021195582699.csv', '1721021195735699.csv', '1721021195583593.csv', '1721021195738424.csv', '1721021195582100.csv', '1721021195743928.csv', '1721021195745381.csv', '1721021195723010.csv', '1721021195550052.csv', '1721021195723986.csv', '1721021195532199.csv', '1721021195543012.csv', '1721021195600839.csv', '1721021195519309.csv', '1721021195593756.csv', '1721021195518765.csv', '1721021195543749.csv', '1721021195725460.csv', '1721021195544740.csv', '1721021195580064.csv', '1721021195750941.csv', '1721021195594005.csv', '1721021195529584.csv', '1721021195713878.csv', '1721021195748897.csv', '1721021195737931.csv', '1721021195754272.csv', '1721021195713139.csv', '1721021195745357.csv', '1721021195719428.csv', '1721021195570803.csv', '1721021195579199.csv', '1721021195551615.csv', '1721021195557264.csv', '1721021195548422.csv', '1721021195572972.csv', '1721021195553770.csv', '1721021195728408.csv', '1721021195586617.csv', '1721021195728346.csv', '1721021195736178.csv', '1721021195589530.csv', '1721021195751849.csv', '1721021195710140.csv', '1721021195569349.csv', '1721021195733941.csv', '1721021195571260.csv', '1721021195563116.csv', '1721021195561701.csv', '1721021195722870.csv', '1721021195564651.csv', '1721021195736805.csv', '1721021195530200.csv', '1721021195522176.csv', '1721021195568719.csv', '1721021195710168.csv', '1721021195560423.csv', '1721021195711276.csv', '1721021195574456.csv', '1721021195581030.csv', '1721021195597652.csv', '1721021195598561.csv', '1721021195580448.csv', '1721021195591551.csv', '1721021195547117.csv', '1721021195575833.csv', '1721021195753680.csv', '1721021195742799.csv', '1721021195555249.csv', '1721021195754845.csv', '1721021195744465.csv', '1721021195742000.csv', '1721021195554816.csv', '1721021195710020.csv', '1721021195521251.csv', '1721021195586978.csv', '1721021195747636.csv', '1721021195748277.csv', '1721021195743875.csv', '1721021195598005.csv', '1721021195595521.csv', '1721021195737892.csv', '1721021195738579.csv', '1721021195594159.csv', '1721021195548026.csv', '1721021195716848.csv', '1721021195557660.csv', '1721021195594603.csv', '1721021195562195.csv', '1721021195727465.csv', '1721021195541758.csv', '1721021195592500.csv', '1721021195558209.csv', '1721021195744854.csv', '1721021195745592.csv', '1721021195722509.csv', '1721021195753496.csv', '1721021195578654.csv', '1721021195714736.csv', '1721021195713059.csv', '1721021195712421.csv', '1721021195714050.csv', '1721021195725299.csv', '1721021195754460.csv', '1721021195719206.csv', '1721021195567760.csv', '1721021195557853.csv', '1721021195546786.csv', '1721021195744883.csv', '1721021195563248.csv', '1721021195522566.csv', '1721021195571658.csv', '1721021195551588.csv', '1721021195744614.csv', '1721021195594857.csv', '1721021195585796.csv', '1721021195743609.csv', '1721021195745536.csv', '1721021195555951.csv', '1721021195750885.csv', '1721021195529326.csv', '1721021195747453.csv', '1721021195756238.csv', '1721021195753340.csv', '1721021195737639.csv', '1721021195734442.csv', '1721021195555004.csv', '1721021195523192.csv', '1721021195543100.csv', '1721021195723658.csv', '1721021195720379.csv', '1721021195586512.csv', '1721021195733463.csv', '1721021195560097.csv', '1721021195550140.csv', '1721021195745287.csv', '1721021195743190.csv', '1721021195711359.csv', '1721021195567277.csv', '1721021195726287.csv', '1721021195579707.csv', '1721021195564756.csv', '1721021195758017.csv', '1721021195549808.csv', '1721021195722036.csv', '1721021195543470.csv', '1721021195714584.csv', '1721021195713599.csv', '1721021195585231.csv', '1721021195568187.csv', '1721021195579934.csv', '1721021195559414.csv', '1721021195723472.csv', '1721021195733661.csv', '1721021195574586.csv', '1721021195566182.csv', '1721021195570938.csv', '1721021195740843.csv', '1721021195735562.csv', '1721021195739358.csv', '1721021195734085.csv', '1721021195568024.csv', '1721021195523541.csv', '1721021195572068.csv', '1721021195521430.csv', '1721021195575049.csv', '1721021195710669.csv', '1721021195722803.csv', '1721021195522677.csv', '1721021195589594.csv', '1721021195712718.csv', '1721021195542197.csv', '1721021195549997.csv', '1721021195737229.csv', '1721021195583052.csv', '1721021195751190.csv', '1721021195575934.csv', '1721021195737573.csv', '1721021195561941.csv', '1721021195552810.csv', '1721021195744006.csv', '1721021195716754.csv', '1721021195567897.csv', '1721021195522313.csv', '1721021195724902.csv', '172102

In [101]:
folder_t = folder + 'train/'
files = os.listdir(folder_t)
files = [file for file in files if file.endswith('.csv')]
# fileNames = []
# siteConv = []
# timeConv = []
# siteQuals = []
# sitePoses = []
# numAg = []
submeta = pd.DataFrame([],columns=meta.columns)

for file in files:
    row = meta.loc[meta.file_name==file].values
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # fileNames.append(row.file_name)
    # siteConv.append(row.site_converged)
    # timeConv.append(row.time_converged)
    # siteQuals.append(row.site_qualities)
    # sitePoses.append(row.site_positions)
    # numAg.append(row.num_agents)
    # break
submeta.to_csv(folder_t+'metadata.csv')
# row
# [(fileName, site_conv, time_conv, entry, folder, folder_graph1, folder_graph2)

In [105]:
# folder = 'data/quorum_sims_all/'
print(folder)
folderto = folder + 'test/'
files = os.listdir(folder)
files = [file for file in files if file.endswith('.csv') and file.startswith('1') and file in files_to_save_one_graph]
for file in files:
    # if np.random.random() < 0.7:
    # print(file)
    shutil.move(folder+file, folderto+file)

./data/multirunsims/

In [106]:
folder_test = folder + 'test/'
files = os.listdir(folder_test)
files = [file for file in files if file.endswith('.csv')]
# fileNames = []
# siteConv = []
# timeConv = []
# siteQuals = []
# sitePoses = []
# numAg = []
submeta = pd.DataFrame([],columns=meta.columns)

for file in files:
    row = meta.loc[meta.file_name==file].values
    try:
        submeta.loc[-1] = row[0]  # adding a row
    except:
        pdb.set_trace()
    # break
    submeta.index = submeta.index + 1  # shifting index
    submeta = submeta.sort_index()  # sorting by index
    # fileNames.append(row.file_name)
    # siteConv.append(row.site_converged)
    # timeConv.append(row.time_converged)
    # siteQuals.append(row.site_qualities)
    # sitePoses.append(row.site_positions)
    # numAg.append(row.num_agents)
    # break
submeta.to_csv(folder_test+'metadata.csv')
# row
# [(fileName, site_conv, time_conv, entry, folder, folder_graph1, folder_graph2)